"""arms table

Revision ID: a24bc63a8489
Revises: 
Create Date: 2020-05-10 02:58:28.980498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24bc63a8489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rest_arm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_count_in_stack', sa.Integer(), nullable=True),
    sa.Column('_country_of_origin', sa.String(), nullable=True),
    sa.Column('_serial_number', sa.String(), nullable=True),
    sa.Column('_operation_crew_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_serial_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rest_arm')
    # ### end Alembic commands ###
